# Generated by Django 4.2.2 on 2023-06-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_grade_student_alter_grade_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade', to='students.grade'),
        ),
    ]
