# Generated by Django 4.2.2 on 2023-06-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
        ('user', '0002_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='students.grade'),
        ),
    ]
