# Generated by Django 4.2.2 on 2023-06-28 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_grade_student_alter_grade_teacher'),
        ('user', '0003_alter_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='students.grade'),
        ),
    ]
